-- =====================================================
-- Register RMAN Backup Info
-- =====================================================
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE IF NOT EXISTS sys.rman_backup_registry (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    backup_type     VARCHAR2(30),
    level_type      VARCHAR2(10),
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    status          VARCHAR2(20),
    location        VARCHAR2(200)
);

INSERT INTO sys.rman_backup_registry (backup_type, level_type, start_time, end_time, status, location)
VALUES ('&1', '&2', SYSTIMESTAMP, SYSTIMESTAMP, '&3', '&4');

COMMIT;

PROMPT RMAN backup registry updated.

