SET LINESIZE 150
COLUMN TABLESPACE_NAME FORMAT A25
SELECT TABLESPACE_NAME,
       ROUND((USED_SPACE*8)/1024,2) USED_MB,
       ROUND((TABLESPACE_SIZE*8)/1024,2) TOTAL_MB,
       ROUND((USED_SPACE/TABLESPACE_SIZE)*100,2) USED_PCT
FROM DBA_TABLESPACE_USAGE_METRICS
ORDER BY USED_PCT DESC;

EXIT;

