#!/bin/bash
# verify_auditing.sh
sqlplus -s sys/Myles003@//localhost:1539/freepdb1 as sysdba <<EOF
COL USERNAME FORMAT A15
COL ACTION_NAME FORMAT A20
SELECT USERNAME, ACTION_NAME, RETURNCODE, EXTENDED_TIMESTAMP FROM DBA_AUDIT_TRAIL ORDER BY EXTENDED_TIMESTAMP DESC FETCH FIRST 10 ROWS ONLY;
EOF

