-- Enforce password complexity
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME 90;
ALTER PROFILE DEFAULT LIMIT PASSWORD_GRACE_TIME 7;
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS 5;

-- Lock default accounts
ALTER USER OUTLN ACCOUNT LOCK;
ALTER USER DBSNMP ACCOUNT LOCK;

-- Audit SYSDBA connections
AUDIT CONNECT BY SYSDBA BY ACCESS;

