-- Create a read-only role for application users
CREATE ROLE APP_READ_ONLY;
GRANT CREATE SESSION TO APP_READ_ONLY;
GRANT SELECT ANY TABLE TO APP_READ_ONLY;

-- Create a DBA limited role for maintenance
CREATE ROLE MAINT_DBA;
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE TO MAINT_DBA;

EXIT;

