-- Drop existing tablespaces if re-running lab
ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLESPACE app_index INCLUDING CONTENTS AND DATAFILES';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -00959 THEN
        RAISE;
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLESPACE app_data INCLUDING CONTENTS AND DATAFILES';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -00959 THEN
        RAISE;
    END IF;
END;
/

PROMPT Tablespaces dropped successfully.

