-- Enable Unified Auditing
ALTER SYSTEM SET audit_trail=DB, EXTENDED SCOPE=SPFILE;
SHUTDOWN IMMEDIATE;
STARTUP;

-- Audit key actions
AUDIT CREATE USER BY ACCESS;
AUDIT DROP USER BY ACCESS;
AUDIT ALTER SYSTEM BY ACCESS;
AUDIT ROLE BY ACCESS;

