-- =====================================================
-- Simulate RMAN Backup Log Table
-- =====================================================
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE IF NOT EXISTS sys.backup_registry (
    backup_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    backup_name     VARCHAR2(100),
    backup_type     VARCHAR2(50),
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    status          VARCHAR2(20),
    comments        VARCHAR2(200)
);

INSERT INTO sys.backup_registry (backup_name, backup_type, start_time, end_time, status, comments)
VALUES ('FULL_DB_SIM_BACKUP', 'FULL', SYSTIMESTAMP, SYSTIMESTAMP, 'COMPLETED', 'Simulated backup registered successfully.');

COMMIT;

PROMPT Backup registry updated with simulated backup entry.

