-- Create wallet and enable auto-login
ADMINISTER KEY MANAGEMENT CREATE KEYSTORE '/opt/oracle/admin/wallet' IDENTIFIED BY MySecurePwd;
ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY MySecurePwd;
ADMINISTER KEY MANAGEMENT SET ENCRYPTION KEY IDENTIFIED BY MySecurePwd WITH BACKUP;

-- Encrypt tablespace
ALTER TABLESPACE USERS ENCRYPTION ONLINE USING 'AES256' ENCRYPT;

